spring:
  output:
    ansi:
      enabled: ALWAYS # 配置控制台输出的效果，彩色、
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_security?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mmsszsd666
server:
  port: 8080
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml